RANDOM_SEED: 0
DATA:
  ROOT: datasets/imagenet
  IMAGE_TRANSFORM_TRAIN:
    - random_resized_crop
    - horizontal_flip
    - normalize
  IMAGE_TRANSFORM_VAL:
    - smallest_resize
    - center_crop
    - normalize

MODEL:
  LINEAR_CLF:
    LAYER_NAME: layer4
    NUM_CLASSES: 1000
    NORM_LAYER: FrozenBN

OPTIM:
  BATCH_SIZE: 256
  OPTIMIZER_NAME: sgd
  SGD_MOMENTUM: 0.9
  SGD_NESTEROV: True
  WEIGHT_DECAY: 0.0001
  NO_DECAY: ""

  LR: 0.01
  WARMUP_STEPS: 0
  LR_DECAY_NAME: multistep
  LR_GAMMA: 0.1
  LR_STEPS:
    - 40032  # 8 epochs
    - 80064  # 16 epochs
    - 120128  # 24 epochs
  NUM_ITERATIONS: 140112  # 28 epochs
