DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("voc_2007_test",)
  
INPUT:
  FORMAT: RGB
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
  
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  META_ARCHITECTURE: GeneralizedRCNN
  BACKBONE:
    NAME: build_resnet_backbone
    FREEZE_AT: 0
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    NORM: SyncBN
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: Res5ROIHeads
    NUM_CLASSES: 20

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025

  GAMMA: 0.1
  STEPS: (12000, 16000)
  MAX_ITER: 18000  # 17.4 epochs
  WARMUP_ITERS: 100

VERSION: 2
