DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("voc_2007_test",)
  
INPUT:
  # Torchvision models use RGB format.
  FORMAT: RGB
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800

MODEL:
  META_ARCHITECTURE: GeneralizedRCNN
  BACKBONE:
    NAME: build_resnet_backbone
    FREEZE_AT: 0                   # MoCo trains all layers end-to-end

  # MoCo finetunes with SyncBN. `STRIDE_IN_1X1: False` is important
  # for	torchvision pre-trained	models!
  RESNETS:
    DEPTH: 50
    NORM: SyncBN
    STRIDE_IN_1X1: False

  # res5 is in head for C4 backbone. MoCo adds extra SyncBN after res5.
  # Refer `scripts/detectron2_tasks.py` for global config hack.
  # Patched D2 built from https://github.com/kdexd/detectron2 (moco-patch branch)
  ROI_HEADS:
    NAME: Res5ROIHeads
    NUM_CLASSES: 20

  # Pre-trained weights are loaded in script, refer `scripts/detectron2_tasks.py`
  WEIGHTS: ""
  MASK_ON: False

  # Color mean from torchvision multiplied by 255.
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]

SOLVER:
  # For 8 GPUs, scale linearly for different number of GPUs.
  IMS_PER_BATCH: 8
  BASE_LR: 0.01

  GAMMA: 0.1
  STEPS: (24000, 32000)
  MAX_ITER: 36000  # 34.8 epochs
  WARMUP_ITERS: 100

VERSION: 2
