RANDOM_SEED: 0
FP16_OPT: 0

DATA:
  TRAIN_LMDB: data/serialized/gcc_train1.1.0.lmdb
  VAL_LMDB: data/serialized/gcc_val1.1.0.lmdb
  CAPTION_CORPUS: data/gcc_train1.1.0_corpus.txt

  IMAGE:
    RESIZE_SIZE: 256
    CROP_SIZE: 224
    COLOR_NORMALIZE: true
    RANDOM_FLIP: true
    PHOTOMETRIC_AUG: true

  CAPTION:
    VOCAB_SIZE: 16000
    MAX_LENGTH: 30
    TOKENIZER: SentencePieceBPETokenizer

MODEL:
  NAME: bicaptioning
  VISUAL:
    NAME: torchvision::resnet50
    PRETRAINED: false
  TEXTUAL:
    NAME: allfuse_prenorm::L2_H512_A8_F2048
    HIDDEN_SIZE: 512
    ATTENTION_HEADS: 8
    FEEDFORWARD_SIZE: 2048
    NUM_LAYERS: 2
  DROPOUT: 0.1

OPTIM:
  NUM_ITERATIONS: 1000000
  OPTIMIZER_NAME: adamw
  ADAM_BETAS: [0.9, 0.98]
  USE_LOOKAHEAD: True

  BATCH_SIZE_PER_GPU: 64
  BATCH_SIZE_MULTIPLIER: 1

  LR: 0.0004
  CNN_LR: 0.02
  WEIGHT_DECAY: 1e-2
  CNN_WEIGHT_DECAY: 1e-2
  LR_DECAY_NAME: cosine
  WARMUP_STEPS: 4000
  CLIP_GRAD_NORM: 10

DOWNSTREAM:
  VOC07_CLF:
    DATA_ROOT: data/VOC2007
    BATCH_SIZE: 64
    LAYER_NAMES: ["layer4"]
    SVM_COSTS: [0.01, 0.1, 1.0, 10.0]

