RANDOM_SEED: 0
FP16_OPT: 2

DATA:
  TRAIN_LMDB: datasets/serialized/gcc_train1.1.0.lmdb
  VAL_LMDB: datasets/serialized/gcc_val1.1.0.lmdb
  CAPTION_CORPUS: datasets/gcc_train1.1.0_corpus.txt

  IMAGE:
    RESIZE_SIZE: 256
    CROP_SIZE: 224
    COLOR_NORMALIZE: true
    RANDOM_FLIP: true
    PHOTOMETRIC_AUG: true

  CAPTION:
    VOCAB_SIZE: 16000
    MAX_LENGTH: 40
    TOKENIZER: SentencePieceBPETokenizer

MODEL:
  NAME: bicaptioning
  VISUAL:
    NAME: torchvision::resnet50
    PRETRAINED: false
  TEXTUAL:
    NAME: allfuse_prenorm::L1_H768_A12_F3072
    HIDDEN_SIZE: 768
    ATTENTION_HEADS: 12
    FEEDFORWARD_SIZE: 3072
    NUM_LAYERS: 1
  DROPOUT: 0.1

OPTIM:
  NUM_ITERATIONS: 4000000
  OPTIMIZER_NAME: sgd
  SGD_MOMENTUM: 0.9
  USE_LOOKAHEAD: True

  BATCH_SIZE_PER_GPU: 64
  BATCH_SIZE_MULTIPLIER: 1

  LR: 0.002
  CNN_LR: 0.2
  WEIGHT_DECAY: 1e-4
  CNN_WEIGHT_DECAY: 1e-4
  LR_DECAY_NAME: cosine
  WARMUP_STEPS: 10000
  CLIP_GRAD_NORM: 10

DOWNSTREAM:
  VOC07_CLF:
    DATA_ROOT: datasets/VOC2007
    BATCH_SIZE: 64
    LAYER_NAMES: ["layer4"]
    SVM_COSTS: [0.01, 0.1, 1.0, 10.0]

