RANDOM_SEED: 0
FP16_OPT: 2

DATA:
  TRAIN_LMDB: datasets/serialized/coco_train2017.lmdb
  VAL_LMDB: datasets/serialized/coco_val2017.lmdb
  CAPTION_CORPUS: datasets/coco_train2017_corpus.txt
  SHUFFLE_TRAIN: True

  IMAGE:
    CROP_SIZE: 224
    COLOR_NORMALIZE: true
    RANDOM_FLIP: true

  CAPTION:
    VOCAB_SIZE: 10000
    MAX_LENGTH: 30
    TOKENIZER: SentencePieceBPETokenizer

MODEL:
  NAME: bicaptioning
  VISUAL:
    NAME: torchvision::resnet50
    PRETRAINED: false
  TEXTUAL:
    NAME: allfuse_prenorm::L1_H512_A8_F2048
    HIDDEN_SIZE: 512
    ATTENTION_HEADS: 8
    FEEDFORWARD_SIZE: 2048
    NUM_LAYERS: 1
  DROPOUT: 0.1
  VISUAL_PROJECTION: mlp

OPTIM:
  NUM_ITERATIONS: 1000000
  OPTIMIZER_NAME: sgd
  SGD_MOMENTUM: 0.9
  USE_LOOKAHEAD: True

  BATCH_SIZE_PER_GPU: 32
  LR: 0.002
  CNN_LR: 0.2
  WEIGHT_DECAY: 1e-4
  CNN_WEIGHT_DECAY: 1e-4
  LR_DECAY_NAME: cosine
  WARMUP_STEPS: 10000
  CLIP_GRAD_NORM: 10

DOWNSTREAM:
  VOC07_CLF:
    DATA_ROOT: datasets/VOC2007
    BATCH_SIZE: 64
    LAYER_NAMES: ["layer4"]
    SVM_COSTS: [0.01, 0.1, 1.0, 10.0]
