RANDOM_SEED: 0

DATA:
  VOCABULARY: data/coco_vocabulary.vocab
  TOKENIZER: data/coco_vocabulary.model

  TRAIN_LMDB: data/serialized/coco_train2017.lmdb
  VAL_LMDB: data/serialized/coco_val2017.lmdb
  MAX_CAPTION_LENGTH: 30

MODEL:
  LINGUISTIC:
    HIDDEN_SIZE: 16
    NUM_ATTENTION_HEADS: 4
    NUM_LAYERS: 2

OPTIM:
  BATCH_SIZE: 8
  NUM_ITERATIONS: 50000
  LR: 1e-3
  WEIGHT_DECAY: 1e-3
  CLIP_GRADIENTS: 5
