RANDOM_SEED: 0

DATA:
  VOCABULARY: data/coco_vocabulary.vocab
  TOKENIZER: data/coco_vocabulary.model

  TRAIN_LMDB: data/serialized/coco_train2017.lmdb
  VAL_LMDB: data/serialized/coco_val2017.lmdb
  MAX_CAPTION_LENGTH: 30

MODEL:
  LINGUISTIC:
    HIDDEN_SIZE: 512
    ATTENTION_HEADS: 8
    NUM_LAYERS: 6