RANDOM_SEED: 0

DATA:
  VOCABULARY: data/coco_vocabulary.vocab
  TOKENIZER: data/coco_vocabulary.model

  TRAIN_LMDB: data/serialized/coco_train2017.lmdb
  VAL_LMDB: data/serialized/coco_val2017.lmdb

  NORMALIZE_IMAGE: true
  MAX_CAPTION_LENGTH: 30

PRETEXT:
  MASKED_LM:
    MASK_PROPORTION: 0.15
    MASK_PROBABILITY: 0.8
    REPLACE_PROBABILITY: 0.1

MODEL:
  VISUAL:
    NAME: torchvision::resnet50
    NORM_LAYER: groupnorm
    NUM_GROUPS: 32
    PRETRAINED: false

  TEXTUAL:
    NAME: default::l6-d768-h12
    HIDDEN_SIZE: 768
    NUM_ATTENTION_HEADS: 12
    NUM_LAYERS: 6

OPTIM:
  OPTIMIZER_NAME: adamw
  BATCH_SIZE_PER_GPU: 16
  BATCH_SIZE_MULTIPLIER: 2
  NUM_ITERATIONS: 1000000
  LR: 1e-4
  WARMUP_STEPS: 2000
  WEIGHT_DECAY: 1e-3
  CLAMP_GRADIENTS: 5

DOWNSTREAM:
  VOC07_CLF:
    DATA_ROOT: data/VOC2007
    BATCH_SIZE: 256
    LAYER_NAMES: ["layer3", "layer4"]
    SVM_COSTS: [0.1, 1.0, 2.0]
