RANDOM_SEED: 0

DATA:
  VOCABULARY: data/coco_vocabulary.vocab
  TOKENIZER: data/coco_vocabulary.model

  TRAIN_LMDB: data/serialized/coco_train2017.lmdb
  VAL_LMDB: data/serialized/coco_val2017.lmdb

  NORMALIZE_IMAGE: true
  MAX_CAPTION_LENGTH: 30

PRETEXT:
  MASKED_LM:
    MASK_PROPORTION: 0.15
    MASK_PROBABILITY: 0.8
    REPLACE_PROBABILITY: 0.1

MODEL:
  VISUAL:
    NAME: torchvision::resnet50
    PRETRAINED: false

  LINGUISTIC:
    HIDDEN_SIZE: 512
    NUM_ATTENTION_HEADS: 8
    NUM_LAYERS: 6

OPTIM:
  OPTIMIZER_NAME: adamw
  BATCH_SIZE_PER_GPU: 32
  BATCH_SIZE_MULTIPLIER: 1
  NUM_ITERATIONS: 400000
  LR: 2e-5
  WARMUP_STEPS: 2000
  WEIGHT_DECAY: 1e-4
  CLAMP_GRADIENTS: 5

  DOWNSTREAM:
    VOC07_CLF:
      DATA_ROOT: data/VOC2007
      BATCH_SIZE: 256
      LAYER_NAMES: ["layer3", "layer4"]
      SVM_COSTS: [0.1, 1.0, 2.0]
