RANDOM_SEED: 0

DATA:
  VOCABULARY: data/coco_vocabulary.vocab
  TOKENIZER: data/coco_vocabulary.model

  TRAIN_LMDB: data/serialized/coco_train2017.lmdb
  VAL_LMDB: data/serialized/coco_val2017.lmdb

  NORMALIZE_IMAGE: true
  MAX_CAPTION_LENGTH: 30

MODEL:
  VISUAL:
    NAME: torchvision::resnext101_32x8d
    PRETRAINED: false

  LINGUISTIC:
    HIDDEN_SIZE: 768
    NUM_ATTENTION_HEADS: 12
    NUM_LAYERS: 12

OPTIM:
  OPTIMIZER_NAME: adamw
  BATCH_SIZE: 64
  GRAD_ACCUMULATION_STEPS: 1
  NUM_ITERATIONS: 200000
  LR: 1e-4
  WARMUP_PROPORTION: 0.1
  WEIGHT_DECAY: 1e-3
  CLIP_GRADIENTS: 10
