RANDOM_SEED: 0
FP16_OPT: 0

DATA:
  TRAIN_LMDB: data/serialized/coco_train2017.lmdb
  VAL_LMDB: data/serialized/coco_val2017.lmdb
  CAPTION_CORPUS: data/coco_train2017_corpus.txt

  IMAGE:
    RESIZE_SIZE: 256  # 192
    CROP_SIZE: 224  # 168
    COLOR_NORMALIZE: true
    RANDOM_FLIP: true
    PHOTOMETRIC_AUG: true

  CAPTION:
    VOCAB_SIZE: 10000
    MAX_LENGTH: 30
    TOKENIZER: SentencePieceBPETokenizer

PRETEXT:
  WORD_MASKING:
    MASK_PROPORTION: 0.15
    MASK_PROBABILITY: 1.0
    REPLACE_PROBABILITY: 0.0

MODEL:
  NAME: bicaptioning
  VISUAL:
    NAME: torchvision::resnet50
    NORM_LAYER: BN
    NUM_GROUPS: 32
    PRETRAINED: false
  TEXTUAL:
    NAME: postnorm_gelu::L1_H512_A8_F2048
    HIDDEN_SIZE: 512
    ATTENTION_HEADS: 8
    FEEDFORWARD_SIZE: 2048
    NUM_LAYERS: 1
    DROPOUT: 0.1
  FUSION:
    NAME: multihead
    PROJECTION_SIZE: 512
    ATTENTION_HEADS: 8
    DROPOUT: 0.1

OPTIM:
  NUM_ITERATIONS: 500000
  OPTIMIZER_NAME: adamw
  ADAM_BETA1: 0.9
  ADAM_BETA2: 0.98
  USE_LOOKAHEAD: True

  BATCH_SIZE_PER_GPU: 64
  BATCH_SIZE_MULTIPLIER: 1

  LR: 1e-4
  CNN_LR: 1e-2
  WEIGHT_DECAY: 1e-2
  CNN_WEIGHT_DECAY: 1e-4
  LR_DECAY_NAME: cosine
  WARMUP_STEPS: 10000
  CLIP_GRAD_NORM: 10

DOWNSTREAM:
  VOC07_CLF:
    DATA_ROOT: data/VOC2007
    BATCH_SIZE: 64
    LAYER_NAMES: ["layer3", "layer4"]
    SVM_COSTS: [0.01, 0.1, 1.0, 10.0]
