RANDOM_SEED: 0
MIXED_PRECISION_OPT: 0

DATA:
  VOCABULARY: data/coco_vocabulary.vocab
  TOKENIZER: data/coco_vocabulary.model

  TRAIN_LMDB: data/serialized/coco_train2017.lmdb
  VAL_LMDB: data/serialized/coco_val2017.lmdb

  NORMALIZE_IMAGE: true
  MAX_CAPTION_LENGTH: 30

PRETEXT:
  WORD_MASKING:
    MASK_PROPORTION: 0.15
    MASK_PROBABILITY: 1.0
    REPLACE_PROBABILITY: 0.0
  MOCO:
    FEATURE_SIZE: 128
    MOMENTUM: 0.999
    QUEUE_SIZE: 4096
    TEMPERATURE: 0.07

MODEL:
  NAME: word_masking
  VISUAL:
    NAME: torchvision::resnet50
    NORM_LAYER: groupnorm
    NUM_GROUPS: 32
    PRETRAINED: false
  TEXTUAL:
    NAME: default::L1_H512_A8
    HIDDEN_SIZE: 512
    NUM_ATTENTION_HEADS: 8
    NUM_LAYERS: 1
    ACTIVATION: gelu
    DROPOUT: 0.1
  FUSION:
    NAME: multihead
    PROJECTION_SIZE: 512
    NUM_ATTENTION_HEADS: 8
    DROPOUT: 0.1

OPTIM:
  OPTIMIZER_NAME: adamw
  BATCH_SIZE_PER_GPU: 64
  BATCH_SIZE_MULTIPLIER: 1
  NUM_ITERATIONS: 500000
  LR: 1e-4
  WARMUP_STEPS: 10000
  WEIGHT_DECAY: 1e-4
  CLAMP_GRADIENTS: 10

DOWNSTREAM:
  VOC07_CLF:
    DATA_ROOT: data/VOC2007
    BATCH_SIZE: 256
    LAYER_NAMES: ["layer3", "layer4"]
    SVM_COSTS: [0.01, 0.1, 1.0, 10.0]
